# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Update Search Index

on:
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Update Search Index
        uses: hmu332233/issue-search/.github/actions/update-search-index@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ALGOLIA_ID: ${{ secrets.ALGOLIA_ID }}
          ALGOLIA_KEY: ${{ secrets.ALGOLIA_KEY }}
          ALGOLIA_INDEX: ${{ secrets.ALGOLIA_INDEX }}
